[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tax_report_generation"
version = "1.0.0"
dependencies = [
    "pandas",
]

[project.optional-dependencies]
test = [
    "pytest",
]

